version: '3.4'

services:

  app-microservice-basic-api:
    container_name: app-microservice-basic-api-icxl
    image: registry.cn-shanghai.aliyuncs.com/icxl-pu/icxl_go:1011_3
    ports:
      - "8086:8086"
#    environment:
#      - GIN_MODE=release
    networks:
      icxl-work:
        aliases:
          - yqgs-basicapi1
    restart: always

networks:
  icxl-work:
   # driver: overlay
      


 